### PR TITLE
DNM Hot Fix: Flavor Text

### PR DESCRIPTION
**Pull request by ORCACommander**

### CODE REVIEW

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 226e9e9cd707fe7f9800cedfef407383466517d9
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 1683fad21c1bc8fc371662b3d0a6353370df3ea9

**Comment by ORCACommander** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6116

reference

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9773b6b469ea23048444458f3f58ac98e97a8205
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 879239aefa64cbe85ae2a01df4398fd8d422b694

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 145671e2f2c6e0ba0f7afa06959deb5341706c68
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: b5ae3c278a72d1938067d33da616b5cff3a39da9

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 145671e2f2c6e0ba0f7afa06959deb5341706c68
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 57412b7662d3ade3e34fe3c13bfd3acf0a04b7ee

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 51ee4292fc0abc032c110b445127ab9725067e5a
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 27cec7a3a67010696a531376806e00411657c6d6

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: f8818db22c792335151ac66cd4a1afb0a5bab1c1
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: f715698007bcd74b9df96f69fa91710497085649

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1e50e17d3624d2101630f4c9508e050f46e3fa8e
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 03310ab5c32460ea415ea0476f60932a2b774ab3

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 28a3734787c0009f815fbb0f75d601005deca47c
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: cb322b1de3b11f0a4ffdce135740743c9663fd6c

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0fa13636950e587127c0a65aed742352489f470b
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: a6f9fa92ac573c5f66d2f0cde046bae402367c69

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1ff8a2bf6b7a87d626376f8289e1fa1ec75d724f
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 760195666ef52f57a2c04d13b6f53ea139d084b2

##### Comment
Not sure if we want to go this route

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 617277c445205c68df3570260d5a65e206f49a12
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: ff5fec893804ed06d7fa78fd89ba0050821c1087

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: bae5250590a4a6caea1207ecf4d769b809b446f5
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: e89552c252b1c740733439e4ed2d253dd5b5f8e7

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2fc681d37f6789ae06bf5f62296af9b6a640ea0c
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: e9751f131e08abdcafcfd848e5ff5f89c2918a7b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2b15221424fa3fdc7463e044e7f0ebd3492daf91
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 9fa40da5b30d1e320e84031eefbbdaffdbd6c8a7

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2b15221424fa3fdc7463e044e7f0ebd3492daf91
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: a9b992eee8c8b6d9f847e582747de2894321d1b7

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 000969547405264e9a6447b62d9acd05b91a5c6e
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 14cbf175946a165b5f400f3b48e351b8010b89c2

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2bcc2a7b0f06a8d6819d9f267e411161bdeac703
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: fcc933c5759bb5b3da46378c35e7b4522eff121c

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: f94d4140ebbc1788249595ea1467818d1842bab0
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: a93eff361724d6b5fc0a3c275ca88c61c46e4f1d

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: e8b4b19df10777c39d6019bc616d21cd3d90e434
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 120a25543e91284596deb94dd56273b3cdfd06c6

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0141b107e8116e94c4022d544faaad8f2e06c886
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: bd8fbcb76a2978da31d4481bacb224374f9fef35

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8d0ef137c7432cabbd448dcb6d0ac417a7fa3a09
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: c3f3477800aea0121600b492c437fbd051b7f7bc

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: d949c335e433e20026627629d337967cb67617fd
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 05a1a400104863d5acf3cf877f3c4b0c5064d683

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2e51e121b4e1a60704a41b76a77085c641126a9f
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: ee0e88c95593cf54e499d1f8c8027d191451e73c

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: f25cf81726aa02d674297316e98f221694f3b815
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: f68677a1725a991a5a3adfb1a5574d5d0a7861f5

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: b4b281db4fce6fa562cdd41a6c0c99f2437a3e32
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: dc812176453d0566ca5bf3b5940e889a87dcbb6c

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0b736da3c86adc7a19d9419f278546d97aaaf599
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 4877db72369725362543344744e8ff736608184c

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 11f0b6850b52d21ea29a563edb537cbbb9f13c2a
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 5af01cf7aceabd3dd006f15879599b43b567cf91

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 11f0b6850b52d21ea29a563edb537cbbb9f13c2a
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 4f42dd5000dd6550431055107c9adf268b93b1ab

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 6e0671ba391e786edffea274eaba0b747b321b7a
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 5eaf75ce11e53b65e5bdefc6fa7e98bba1c27a59

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8ff783173a3c972fb437afabb99e0a07d1cd4d93
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: e8a52b78c65775477dfc1120d9ac03ce657241d0

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: ff542d36a2034db022d5a5472f7d6afe9359c7f4
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 9e0c98826dd70da1b403646ab1f672cc8e343337

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1a17c21c40dac421ff272a394d92c6d3ff0aa48f
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 951f30e7413ddeb08fef72b8b691bb3e42729f70

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: cd7e85ad4dc719fed2cb0dee036afd66d3fb155c
Pull Request: 97d730ee799bddc396185915a8ffbe1766dadc9e
Server: 9053331774c50f95fa84b67a66b1e6d38dd6a019

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request closed without merging**
