### PR TITLE
Free Entertainment

### PR DESCRIPTION
**Pull request by ORCACommander**
Removes clown and mime from the veteran requirements

### CODE REVIEW

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0e7589fe7bdc44c38405c82e4f764fbc293cdaae
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: e735c7ebd9f7a6a2b0003a4b347d46fbf9b150d9
</details>

**Comment by Werenimal** [comment]
POG

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: aae863ea7cbe90ac8e0e86c54452b4e29db93853
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: 9ce13552134e82bff13d17877bb49589bef6b7aa
</details>

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 4856e04436751cad258e1d46f1f0c33f93cce3a1
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: 6f5d74b367d1eb5367b03fd46540baa0dc28b193
</details>

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9d74eacdb5c8e1d2567cfa22a3e204dea5ba71bd
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: a2806f9da2d64f929fd65f8fa88e9d3ba31db992
</details>

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 79065d37e6a2ee87d5b2ca2dd938b3a09c3166cd
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: 4e63da30e4479b660ebec1ae44a29fb0e442bb1d
</details>

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 4e2150228d370f5625fa6225963fd6fd1eb02b3c
Pull Request: 352cd28f51dd809c1ff75ecfd1d535a910749aad
Server: ba4f0e8fd283bd627c6c6bfdd78f76aeb816ac13
</details>

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request merged**
