### PR TITLE
Revert "Telemetry 'n shit (#10810)" [TEST MERGE ONLY]

### PR DESCRIPTION
**Pull request by RogueStationAI**
This reverts commit eb384bd2d72a5b23dd9785cc06815049d507d3d5.

### CODE REVIEW

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: c9a1dbf81ee7149e242f524a6ec0cbc714283e10
Pull Request: 58ec1837029b33842b8ad9d6d12a752de6f23026
Server: a9b3848f30b8492439f193423970d7697880c1b4

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: f41312ecbfce38b8accfb6937bc44ce34b596df8
Pull Request: 58ec1837029b33842b8ad9d6d12a752de6f23026
Server: cf40abde48b0cdfb069435301db1568f4c6b7ef0

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 4500f882b551aabfe210d8221a8b69f99801337a
Pull Request: 58ec1837029b33842b8ad9d6d12a752de6f23026
Server: e1063f2685fb3ef18648daeb5966e37e40c6751b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 6a00b10bd80072d86cea2ad2f7b64d224ae44a0d
Pull Request: 58ec1837029b33842b8ad9d6d12a752de6f23026
Server: dad349ac5250f343bcc333421e87abe460d156be

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 5023771c2f362301d0c4aa7b942b0401fa01a532
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: c8d2356a8185b82ddd97792c2d68178c4e1ce420

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 4b720dec4c3df0b80deada1d12210404682223a4
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 1803906ac21506940a7dab803bec3e59bd5d1017

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: e2ed9052bb865be3fd6577f3c70e7ba63de8b1dd
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 72adcbd301e4208056b556bc453c657cf62b50eb

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 99cf68a24085aeb3bfa4a526bff358fb4c026403
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: a90181ed8a9da3c5fdf00776d9d25fcbc00618e1

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: fcd2bc4e3f4d455c27efa583f2ef57d7c76b696e
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 29c87f2f6b4e8b1ea8e5c9cdbea0031c66713741

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: d5114f91dd2d879b0453a1475bf02460c1acffee
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 1f6aacfdede3fdd6d069a3eb666f8ab7f13ca315

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 2676e0ab8505402f00208d30dde33d1efbb89f72
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: b8ede33e11656657f41ba184d10fe6d6816a4605

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8f1266d03779a86efbfd928eed14f0a5e358f73a
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 2bffb26721d096ed4c75b3224afc9284e5f49752

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 04a3899c5571b3a30f5c7fcdf81108aefcdda45a
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 17b09bad8779d2b208bed69436ecd556d811ec2e

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 308ae37a962e417ac05c01c3cde1d583176ec195
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 180e78c1a3534c1f265536ca7bd34f0207baad28

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: ca43b5a25081d38d3eb8208d59aa5f0bda4eecb6
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 4aea9b60a1b013ebab265bc789201ee8c549bbb2

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: ca43b5a25081d38d3eb8208d59aa5f0bda4eecb6
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 0a163facc6bfabf5b95d2fbaeda7b46ae097fa3a

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3530b56d1f1acb17e92276ab6a4ff7826853bb74
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 0b25e1fe326c4883ddd67966b65a403894be22aa

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: bb67aa2a3aa9b7c17708d91675e70b52524ba518
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 33421ea8a92ccf067e5785a0c05a46e8710dda17

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: bb67aa2a3aa9b7c17708d91675e70b52524ba518
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 2611f9415e35822611fcfcdc39ae909d93e0ad47

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1cb2c0c729946468423033438a00a8a0a3fd6268
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 5cc4bbaac337ae0e114c3d13c85f7b8f1ce39f08

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 92df213ac24a17d42a1a7842fdcc042f7fa79aa8
Pull Request: 75ab1df7d901ace3f0462d8c924e7f47b0a6f20f
Server: 4928a1d205c05488729c8ff9452c3f3d7aef164f

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 23b1eaf7da1d80af45df3fb60e34e91c251bd035
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 8f9f53312cfd9f1571afd3a28ed475065be00ca7

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 29bfefd4db87a36f41d93e34a01b5545e4218382
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 88f4074ab172c1b66d6d3201f8cd8e8e123915ef

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9f9df2273cd0a1e5c66624f7630cb2efdedf559c
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 6214954945e99450c623b1ceed940b094c634118

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 05c60b01cd0fbf8725978e40d0e3bcd19052a939
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 55cacc3316ae58e79d2f54fba2de06ea63f23488

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 5dac9b46d0c4fc48750c24355e686a4708ef94cd
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 02c549f7833f4944f17c4d60da5cfb22498664a6

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: c73d5d3a16906732a78db7141c867b51e83fe6e6
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: e0515398b89a7d5a3df666066bcccbe1c13b76dd

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 7d2ee8c673ee7bb8905a64a546a744fb8f4585f7
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: f5d2f9e7309b5dd65057d338c0552ea9778806f5

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 02a23dd2561b4c7df978eece298f2d668844354c
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 0df30d7851ce9b9e594b4fad53dd76565597420b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9b794ae3c0cb5f9b8ffb4c838ce36cab7da14945
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: a9cc44cf0711a953bc87320100ffd1e93a607127

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 22d4274ee1f576e39897887d75a22e59ffb3084e
Pull Request: ba5834b64467c936a04ff52084a455a8f81ff961
Server: 4eab530aaf2dbeaf08d06c8437bc80cb098af4a5

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: fa10ef798e5a57cbe40702aab2614cb4a819085d
Pull Request: 4902a938a5b1bba2a9b7dbd80ee1cd3aa9cc6e2b
Server: daae4372c66d3aa62a87429e79f7b48aad2f3a10

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3ddd406243def18fee0efcb42bb713cee3b2deb4
Pull Request: 4902a938a5b1bba2a9b7dbd80ee1cd3aa9cc6e2b
Server: d1f80857be61e3f523e7ec4bfc45e64c7946c517

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8bd11c2a0bfda745ba0966d549840c7b18b87fe6
Pull Request: 4902a938a5b1bba2a9b7dbd80ee1cd3aa9cc6e2b
Server: 14451a7672d68b87bed477a80d5d2fd315684747

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0eb264da3f243013d3c97dd9482047daecb84bfd
Pull Request: 4902a938a5b1bba2a9b7dbd80ee1cd3aa9cc6e2b
Server: 066364c8218890f27d29953533b94dafc0dbc896

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9dc0bae1a709a9cae3c20b74aae07c784266fdf7
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 3acb637442d8addf5e8f699633240abc44a1de2a

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 7766370563db7454e38d0dcc3394554d9b51bf8a
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 5ef20695af5dbd2cbc5a747b7b1a176c2a1ebcee

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: c70f33d848198ca516ae9198e33f07c3fe4650f9
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: b9030a4e84161e5b18cc234fbf7ecced72f0de9f

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: ffa06056316cea10f1ddfdd4ccec8fa2bf3bd2bf
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 77a0bbc2130bb8acc83157638540a76554e77e9f

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 02e7557a86604fc7b3fba883ccc8a4c5241b010c
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: a8ea80b6a54b29cc1abe0117de1f9e019dd4570c

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: e0b9e002461be0085be9ecd5885fc4f2b577d763
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: da08d468c86461c581403dc0bc8f5c651f122342

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 5ad15f00d7e2225cfd5f61f4fd0f3d2fd8866c07
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 9080f768dab18dd52f00806bc454264d9f5c8438

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: a5eb38dfaee1f10aed8623e6c0c190bd80f0b327
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 525cf27cf6a8a1c86d04d703ce88f9e9bde809de

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: b912168b40070e078bac27bbe320a1e35a9c8337
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: dd4d9122d62af6458d8f61142a092f9d808a7055

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3bfc9414c18af6bcfbefab0fef0f69c4f7b25503
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 510a3aa164c113624324f010d3a82e635426b2ec

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 748d7812883995a187dfec13e6105fd4a336b3ba
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 980e9bd109f30d717fb8c20df22dc923caf1c149

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0bd5a8d83136a734c4fc09f3557967182fea2fc5
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: d4b8b6e05913b2d6429844ab5c0c73188f9d4719

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8ae4ea8b7db2db3340ee80653f9720425bae063d
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: b670b8edcf26d272a9fa0f50066ec3ea27d74663

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 91fdf1b8efa6a14072a2c2e66c0365aef41e7593
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 62a33d34557d77b992653665feee52651ec6f90d

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: d4b4551d62ec529391efbb21eb3f72a182466543
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: b055c40919c7c9d6df02f508f48d2154cf6a8991

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1227dd421603bccbe654e87ba75b67ee45524d2e
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: b64a77b787ef7e1418e11011aac8a86d610e1b46

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 036df8ead8dd9c3b4d6ed8d89c5d65137bb3a405
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: be93264c5b8cad4e488083e1b6c53b0397a751f6

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 89c8b7e5bfa338511705a7a2e55c2c34abe3b004
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: f2760d48346faa1afbb16b1cfc75ffd3a4ed198e

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 340f1e862f47c6f7be6958caee9f525628301ba5
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: c3da6351b45d7b06cd7bedcfe6888715b565d05b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 7709ec321fce6f575c6254f9fc32a4891ce1ef95
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 690f14bf9cf483c48626c15d288781f3488fc068

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 17641f9fee11778059124fa3c8d4668cfefcfcb6
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 7e1f20f81136d86f8acf72930c71374cf48f538b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: b88e0b3d4107fce69774dfd650168ef14969a6f0
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: bcf5bd1bf3fa8bfbcf3017e9bef973e3737e5a3d

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: cac53539a29fc9b1bcb931558a92022483757e84
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 3f86d27cada45ca92457c74e446cdc7a80c76265

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 74885d203d3ded6dae3f8aac4d2805677f45e0f0
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 3b880c26744d0e24b6b788511d24c12bebc4e947

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 326390fcf70bbb9b95313f0ca7af5342056be0cb
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 445a9b19ad59626668ce4857546b1c44e0894f31

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: a745e063eb63ed4ee38a86895179652864e197ff
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: a147c9ede7999399222c02b8fdc5bcd1e8169efb

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 091faa07f5cf4c720f3e9c9b646af42321399a3a
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 170951bd2e96d12fe9f8d373f04a0dbbdd1dc82a

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 5749264784aa9e2d25e54e7d6ecf9241ab5acb79
Pull Request: 1868c156c8ab2081d7bd3f2209d57ad23faaa6c6
Server: 790ad5698dc16ff09c9219e767ad82e97aa4a1c8

**Comment by ORCACommander** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823

has been deactivated up stream.

Hold on to your butts

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request closed without merging**
