### PR TITLE
[WIP] Pubby Overhaul

### PR DESCRIPTION
**Pull request by Kittayecat**
## About The Pull Request

Finally addresses some of the mass "cram" this map has experienced over time, medbay still suffers a bit from it, but chemistry is atleast more comparable to the floor space of other maps (a bit larger, but im sure more can be done here)

Re-lays-out the whole of atmospherics, parts of science are moves, and chemistry is less "cramped" for the purpose of plumbing (if a little oddly shaped), this needs extensive testing to track down various issues, like disposals and piping so testmerging would be ideal

## Changelog

:cl:
balance: changed up atmos, medbay and research layouts
/:cl:

### CODE REVIEW

**Comment by ORCACommander** [comment]
map render failing since its not passing linters

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: ca43b5a25081d38d3eb8208d59aa5f0bda4eecb6
Pull Request: 5f7b2fcc4e9d0c150ad31e54cd7aec571feba68c
Server: 0a163facc6bfabf5b95d2fbaeda7b46ae097fa3a

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3530b56d1f1acb17e92276ab6a4ff7826853bb74
Pull Request: d92ddd60f80aed26cde2f5a0a4edb9f3ab91531a
Server: 0b25e1fe326c4883ddd67966b65a403894be22aa

**Comment by ORCACommander** [comment]
i think new cameras should be built on the directional templates

**Comment by Kittayecat** [comment]
i've been using the auto-name directional templates for new cameras, old ones were just moved, not sure entirely how they are behaving,

**Comment by ORCACommander** [comment]
ok just checking

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: bb67aa2a3aa9b7c17708d91675e70b52524ba518
Pull Request: d92ddd60f80aed26cde2f5a0a4edb9f3ab91531a
Server: 33421ea8a92ccf067e5785a0c05a46e8710dda17

**Comment by Kittayecat** [comment]
probably best to take this off test merge while its stalled because of some in progress stuff thats stopping me being able to commit any fixes to the current version

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Comment by ORCACommander** [comment]
Up stream BS has been resolved but now we have merge conflicts up the wazoo and most of the newscasters and bounty boards were lost.

Also there was a small refactor on atmos as well so new type paths there as well

**Comment by ORCACommander** [comment]
image

**Comment by ORCACommander** [comment]
image

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 23b1eaf7da1d80af45df3fb60e34e91c251bd035
Pull Request: e42039d2d99e184fe90c01a62bdc4498009b9ab1
Server: 8f9f53312cfd9f1571afd3a28ed475065be00ca7

**Comment by Kittayecat** [comment]
The to-do list currently sits at painting the map, fixing dorms layout (namely gateway + holodeck), and adding appropriate tags to cameras (along with replacing them with the blank direcitonal template and give them appropriate names)

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 29bfefd4db87a36f41d93e34a01b5545e4218382
Pull Request: ffcc07693bb403f6e8a43ea5bcb52212643fb7ac
Server: 88f4074ab172c1b66d6d3201f8cd8e8e123915ef

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9f9df2273cd0a1e5c66624f7630cb2efdedf559c
Pull Request: ffcc07693bb403f6e8a43ea5bcb52212643fb7ac
Server: 6214954945e99450c623b1ceed940b094c634118

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 05c60b01cd0fbf8725978e40d0e3bcd19052a939
Pull Request: ffcc07693bb403f6e8a43ea5bcb52212643fb7ac
Server: 55cacc3316ae58e79d2f54fba2de06ea63f23488

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 5dac9b46d0c4fc48750c24355e686a4708ef94cd
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: 02c549f7833f4944f17c4d60da5cfb22498664a6

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: c73d5d3a16906732a78db7141c867b51e83fe6e6
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: e0515398b89a7d5a3df666066bcccbe1c13b76dd

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 7d2ee8c673ee7bb8905a64a546a744fb8f4585f7
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: f5d2f9e7309b5dd65057d338c0552ea9778806f5

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8c11d23c0d761bcb1c1bc4959003203a55e3a529
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: 96105484872a49e5e8314ddde88f1775818d68bc

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 02a23dd2561b4c7df978eece298f2d668844354c
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: 0df30d7851ce9b9e594b4fad53dd76565597420b

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 9b794ae3c0cb5f9b8ffb4c838ce36cab7da14945
Pull Request: d4ba8d4a6924ed9cf704e335642164bc1191cbb6
Server: a9cc44cf0711a953bc87320100ffd1e93a607127

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 22d4274ee1f576e39897887d75a22e59ffb3084e
Pull Request: 492d478e7660703f0772fb0c63a70c56033a4c9d
Server: 4eab530aaf2dbeaf08d06c8437bc80cb098af4a5

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3b78203dc7aaf26f1b0bc6e4bbfe0fa55cf26034
Pull Request: a4bb8014f6aa706578d9f90c6023ad2f0c8a0319
Server: d304230034e7bec80fd1fb58892b220ff5b1f84d

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: fa10ef798e5a57cbe40702aab2614cb4a819085d
Pull Request: a4bb8014f6aa706578d9f90c6023ad2f0c8a0319
Server: daae4372c66d3aa62a87429e79f7b48aad2f3a10

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 3ddd406243def18fee0efcb42bb713cee3b2deb4
Pull Request: a4bb8014f6aa706578d9f90c6023ad2f0c8a0319
Server: d1f80857be61e3f523e7ec4bfc45e64c7946c517

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 8bd11c2a0bfda745ba0966d549840c7b18b87fe6
Pull Request: a4bb8014f6aa706578d9f90c6023ad2f0c8a0319
Server: 14451a7672d68b87bed477a80d5d2fd315684747

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 6c649dbf6bf2a8261d9392dfcb1797a1490249bf
Pull Request: 2c9f3d5ea580617a89581a419c9fc0f28b0f4de0
Server: bd57b32b9da9556befd1f52a8445c5b85e578058

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0eb264da3f243013d3c97dd9482047daecb84bfd
Pull Request: 2c9f3d5ea580617a89581a419c9fc0f28b0f4de0
Server: 066364c8218890f27d29953533b94dafc0dbc896

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request merged**
