### PR TITLE
Removes the armageddon coronial mass ejection

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

Removes the coronial mass ejection's armageddon intensity setting, it was abused and lead to the server slowing down and crying out in pain multiple times. Not very enjoyable

## How This Contributes To Tannhauser

Players can finally not worry about admin-spawned armageddon CME's, for high amounts of admin abuse please use the much more tame "extreme" variant

## Changelog
:cl:
del: Removed armageddon CME's
/:cl:

### CODE REVIEW

**Comment by Werenimal** [comment]
I recommend against a removal but instead just a rule to not trigger these. The admin who was triggering these was told not to do it anymore at the end of live rounds.

**Comment by Gboster-0** [comment]
> I recommend against a removal but instead just a rule to not trigger these. The admin who was triggering these was told not to do it anymore at the end of live rounds.

I mean, i do usually argue against removals but i feel like removing this one wont take anything out from the game. 
Only admins can trigger this and its so strong that you might aswell just trigger the nuke (in addition to this event completelly destroying da server) there is quite a bit of nothing to save here.

**Comment by ORCACommander** [comment]
if we are to remove it and not trust the admins to dial it back when we take feedback into a account, then removal needs to  maximize code compatibility with SR. is there any way to limit it to just a UI removal?

**Comment by Gboster-0** [comment]
There isnt as far as i know, but to be honest after thinking a bit more the armageddon ejections triggered by admins happened quite rarelly anyway so i no longer think its needed. In addition to the accasional conflicts it could cause it just dosent seem worth it anymore to me

**Pull request closed without merging**
