### PR TITLE
Revert "[MIRROR] Advanced Greyscale Sprite Generation (#4792)"

### PR DESCRIPTION
**Pull request by ORCACommander**
This reverts commit bc6c285adb12b792dbd5c7f1f16607fc6ccac365.

### CODE REVIEW

**Comment by ORCACommander** [comment]
https://github.com/tgstation/tgstation/pull/58313/files

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: fa280c14f439b3b49b353a318ba7cc299335e63e
Pull Request: 06d1432a4f7de483bc9e8e291359eb655ccae65e
Server: 89ff0b6cd02d9068861924106ff9efc1b2f9a51f

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: b8b1310195e9528014ee56c74e1b0103e69527d4
Pull Request: 06d1432a4f7de483bc9e8e291359eb655ccae65e
Server: f9bf0ff6297b0e8843b204f7d7bfecef7c6ef624

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: b968f410a435898894eb74b3931789d698a755cd
Pull Request: 06d1432a4f7de483bc9e8e291359eb655ccae65e
Server: bbc128d9effa48c11c620a6afb86b024a3ac3479

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 557a0311ea249d59970416580b4415280a978dfc
Pull Request: 06d1432a4f7de483bc9e8e291359eb655ccae65e
Server: 3edb7e602c25c43f9c73b84681436de9c7b4167b

**Comment by ORCACommander** [comment]
https://github.com/tgstation/tgstation/pull/58378/files

Looks like we are waiting for this to downstream

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 7dbfce2ccaa198651539a2b557fe3423aed3c30e
Pull Request: 06d1432a4f7de483bc9e8e291359eb655ccae65e
Server: b444ad3dd5dc3d721efe1ed713625d86d263f76a

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request closed without merging**
