### PR TITLE
[MODULAR] Return Of the Plush

### PR DESCRIPTION
**Pull request by ORCACommander**
## About The Pull Request

There are a few Fermi Chemicals on the old Cold Base that were... interesting.

## Why It's Good For The Game

The Plushies are Aware

## Changelog
:cl:
add: Plushmium
/:cl:

### CODE REVIEW

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 145671e2f2c6e0ba0f7afa06959deb5341706c68
Pull Request: 8257899a6202d141092fde89867e465ab1e3737c
Server: b5ae3c278a72d1938067d33da616b5cff3a39da9

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by ORCACommander** [comment]
plushling hunting logic broken?

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 145671e2f2c6e0ba0f7afa06959deb5341706c68
Pull Request: 3b2c8059e74bb481b32c52db42b31cdebae846f8
Server: 57412b7662d3ade3e34fe3c13bfd3acf0a04b7ee

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 51ee4292fc0abc032c110b445127ab9725067e5a
Pull Request: 3b2c8059e74bb481b32c52db42b31cdebae846f8
Server: 27cec7a3a67010696a531376806e00411657c6d6

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: f8818db22c792335151ac66cd4a1afb0a5bab1c1
Pull Request: 85e60ac03dab07b1e5485db0b570a26af3fe5999
Server: f715698007bcd74b9df96f69fa91710497085649

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1e50e17d3624d2101630f4c9508e050f46e3fa8e
Pull Request: 85e60ac03dab07b1e5485db0b570a26af3fe5999
Server: 03310ab5c32460ea415ea0476f60932a2b774ab3

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 28a3734787c0009f815fbb0f75d601005deca47c
Pull Request: 85e60ac03dab07b1e5485db0b570a26af3fe5999
Server: cb322b1de3b11f0a4ffdce135740743c9663fd6c

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 0fa13636950e587127c0a65aed742352489f470b
Pull Request: 85e60ac03dab07b1e5485db0b570a26af3fe5999
Server: a6f9fa92ac573c5f66d2f0cde046bae402367c69

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 1ff8a2bf6b7a87d626376f8289e1fa1ec75d724f
Pull Request: 85e60ac03dab07b1e5485db0b570a26af3fe5999
Server: 760195666ef52f57a2c04d13b6f53ea139d084b2

##### Comment
Disabled Manaforge PR https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/pull/13 due to conlict and this needs tresting.

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request merged**
